services:
  web:
    build: .
    container_name: django_app
    command: sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/app:z
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  worker:
    build: .
    container_name: django_celery_worker_short
    command: celery -A mysite worker --loglevel=info -Q default --concurrency 2
    depends_on:
      - redis
    volumes:
      - .:/app:z
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  worker_automations:
    build: .
    container_name: django_celery_worker_long
    command: celery -A mysite worker --loglevel=info -Q automations --concurrency 3
    depends_on:
      - redis
    volumes:
      - .:/app:z
    environment:
      - DJANGO_SETTINGS_MODULE=mysite.settings.dev
      - CELERY_BROKER_URL=redis://redis:6379/0

  beat:
    build: .
    container_name: django_celery_beat
    command: celery -A mysite beat --loglevel=info --schedule=/tmp/celerybeat-schedule
    depends_on:
      - redis
    volumes:
      - .:/app:z
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  flower:
    build: .
    container_name: django_celery_flower
    command: celery -A mysite flower --address=0.0.0.0 --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - worker
    volumes:
      - .:/app:z
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  redis:
    image: redis:7-alpine
    container_name: django_redis
    ports:
      - "6379:6379"
